import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FormDataProvider } from "../formDetails";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FormDataProvider>{children}</FormDataProvider>
      </body>
    </html>
  );
}
